### ISSUE TITLE
The prices are incorrect

### ISSUE THREAD

**Issue by luotinen** [T3m3z/spotprices2ha#12]
The current electricity price is 5.32 c/kWh but the integration reports 6.86 c/kWh which seems to be the next hours price. Does the integration take in account the winter and summer time correctly?

**Comment by T3m3z** [comment]
This is something that hadn't been really thought when the helper tools
were created. This helper package just assumes that the data source
provides data for each hour. And during the last night one hour was
"skipped" due DST. So the problem should be resolved tomorrow but it will
reoccur when next adjustment due to DST happens. I will try to think
whether there is an easy way to fix this. Jinja2 templates bring some
limitations. But we will see.

Best Regards,
Temez

su 26. maalisk. 2023 klo 17.08 Lauri Uotinen ***@***.***>
kirjoitti:

**Comment by T3m3z** [comment]
Most probably fixed by #21 .
