### ISSUE TITLE
Negative energy prices + vat

### ISSUE THREAD

**Issue by lakofsth** [T3m3z/spotprices2ha#17]
It appears that negative energy prices are not calculated correctly. From a quick look negative VAT is calculated so -0,20 becomes -0,25.

**Comment by lakofsth** [comment]
My calculation was incorrect. But still I'm seeing a discrepancy when the energy price goes negative.

**Comment by lakofsth** [comment]
I've found that more recently this discrepancy is not present. It may have just been some difference in data sources. Closing.

**Comment by lakofsth** [comment]
Re-opening as the issue still seems present

**Comment by T3m3z** [comment]
Hi! The VAT calculations are done on the data source side (https://spot-hinta.fi). I asked from the maintainer of the data source site about this and he had already stumbled upon this question. Based on his research/discussions on other sites, the current calculation method is correct. He explained that the "negative VAT" has to be there or otherwise the "monthly bill" wouldn't mathc. I have no factual reason to believe otherwise so I'm going to close this issue. If you have some source indicating otherwise, please reopen this issue with a link to this source.
