### ISSUE TITLE
Breaks a lot on background 

### ISSUE THREAD

**Issue by viiliainen** [T3m3z/spotprices2ha#24]
I have HA 2023.9.2
After including package automations stops working, cloud base integrations won't load correctly etc. Sonof for example.
Check the system log after restart.. there is a lot.
Spot itself works though.

**Comment by T3m3z** [comment]
Hello and thank you for reporting this issue!

I'm running HomeAssistant version 2023.9.2 and version 0.2.1 of this package. Just restarted my HomeAssistant and I got 0 errors related to this package on my instance. But if it works on my instance doesn't guarantee that it is bug-free.

To ease debuggind, could you please add a complete system log (there is a "Download full log" button there) and your configuration.yaml file here? Please check the files before adding them here so that they don't contain sensitive information like personal data, passwords, etc.

**Comment by viiliainen** [comment]
Hmm.. Uncommented Include, started system and all works ok.
Before starting I disabled Philips Hue (that has some issues) just to get clean log.. 
Maybe it breaks something that you code runs into and then it goes south.

**Comment by T3m3z** [comment]
So, did I understand correctly that your problems are now resolved? Or can you replicate the problem?

If there is something to be investigated and you have logs, then please attach them here. Otherwise I would suggest closing this issue.

**Comment by viiliainen** [comment]
Disabling Hue cleard errors. But seems that running the system in Advanced mode is a must.
If running normal mode and Spot library included, all Sonoff devices are out of reach. Disabling Spot.. and all Sonoff devices are online again.
Running in Advanced both work.
There in nothing on error log to report so this is a bit shady to investigate. And Sonoff seems to be only one affected out of my 19 integrations.

**Comment by T3m3z** [comment]
Ok, very weird and I agree that this is hard to debug. Could you check whether there is a lot of CPU activity or something like that when the problem occurs? You should be able to find that information from Settings -> System -> Hardware (not sure if this is the case for all installations though).

**Comment by T3m3z** [comment]
Inactive issue without necessary information to continue debugging. And this is the only report of problems of this kind. Closing issue. You can reopen this if the problem persists and you have more debugging information available.
